media:
  - name: images
    label: Images
    input: public/assets/images
    output: /assets/images
    categories: [image]

  - name: music
    label: Music
    input: public/assets/music
    output: /assets/music
    categories: [ audio ] 


content:
  - name: posts
    label: Posts
    path: src/content/posts
    type: collection
    #create: true
    #slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    view:
      fields: [pinned, draft, slug, title, author, category, tags, language, published, date ]

    fields:
      # ===== 基础内容 =====
      - { name: title, label: Title, type: string, required: true }
      - { name: body, label: Body, type: rich-text }
    
      # ===== 作者与时间 =====
      - { name: author, label: Author, type: string, required: true }
      - { name: date, label: Date, type: date, required: true }
      - { name: published, label: Published, type: date }
    
      # ===== 内容与分类 =====
      - { name: slug, label: Slug, type: string, required: true }
      - { name: description, label: Description, type: string }
      - { name: category, label: Category, type: select }
      - { name: tags, label: Tags, type: string, list: true }
    
      # ===== 发布控制 =====
      - { name: draft, label: Draft, type: boolean }
      - { name: pinned, label: Pinned, type: boolean }
    
      # ===== 多语言与SEO =====
      - { name: language, label: Language, type: string } 
      - { name: toc, label: Show TOC, type: boolean }    
    
      # ===== 媒体与交互 =====
      - { name: cover, label: Cover Image, type: string }
      - { name: coverIncontent, label: Show Cover in Content, type: boolean }
    
      # ===== 高级功能 =====
      - { name: encrypted, label: Enable Encryption, type: boolean }
      - { name: password, label: Password, type: text }   # 仅在 encrypted=true 时显示
 