media:
  - name: images
    label: Images
    input: public/assets/images
    output: /assets/images
    categories: [image]

  - name: music
    label: Music
    input: public/assets/music
    output: /assets/music
    categories: [ audio ] 


content:
  - name: posts
    label: Posts
    path: src/content/posts
    type: collection
    #create: true
    #slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    view: 
      fields: [pinned, draft, title, author, category, tags, published, date ]

    fields:
    - { name: title, label: Title, type: string, required: true }
    - { name: description, label: Description, type: string }
    - { name: author, label: Author, type: string }
    - { name: pinned, label: Pinned, type: boolean }
    - { name: published, label: Published, type: date }
    - { name: date, label: Date, type: date }
    - { name: tags, label: Tags, type: string, list: true }
    - { name: category, label: Category, type: text }
    - { name: draft, label: Draft, type: boolean }
    - { name: cover, label: Cover Image, type: string }
    - { name: coverIncontent, label: Cover in Content, type: boolean }
    - { name: encrypted, label: Encrypted, type: boolean }
    - { name: password, label: Password, type: text}
    - { name: body, label: Body, type: rich-text}


 